from pathlib import Path
import sys

import yaml


ROOT = Path(__file__).resolve().parents[2]
INFO = ROOT / "info.yaml"
SRC = ROOT / "src"
GENERATED = SRC / "generated.vhdl"


def main():
    with INFO.open("r", encoding="utf-8") as f:
        info = yaml.safe_load(f)

    project = info["project"]
    sources = project["source_files"]

    if not sources:
        raise RuntimeError("project.source_files is empty")

    contents = []

    for source in sources:
        if not source.endswith(".vhdl"):
            raise RuntimeError(
                f"Non-VHDL source in source_files: {source}"
            )

        path = SRC / source

        if not path.is_file():
            raise FileNotFoundError(
                f"VHDL source does not exist: {path}"
            )

        contents.append(
            f"-- BEGIN {source}\n"
            f"{path.read_text(encoding='utf-8')}\n"
            f"-- END {source}\n"
        )

    GENERATED.write_text(
        "-- THIS FILE IS GENERATED BY CI. DO NOT EDIT.\n\n"
        + "\n".join(contents),
        encoding="utf-8",
    )

    # Keep all other project metadata unchanged.
    project["source_files"] = ["generated.vhdl"]

    with INFO.open("w", encoding="utf-8") as f:
        yaml.safe_dump(
            info,
            f,
            sort_keys=False,
            allow_unicode=True,
        )

    print(f"Combined {len(sources)} VHDL sources into {GENERATED}")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)